### ISSUE TITLE
标注工具测试

### ISSUE THREAD

**Issue by MiniBullLab** [MiniBullLab/easy_sample_mark#1]
1.分割标注测试
2.分割转换工具测试
3.整体测试

**Comment by kingwangxiang** [comment]
测最新EasyAiSampleMark标注工具:
1.当前版本软件，分类和分割标注功能都可以工作，可以保存标注结果。不同于上一个版本的是，分割标注，本地没有保存分割的类别mask图。
2.在标注过程中，当遇到图片损坏，未能加载的情况，可否实现自动跳到下一张标注图片上，同时将未能加载图片路径前的方框图标，换红色X或者其他损坏异常标识图标。
![1](https://user-images.githubusercontent.com/37147736/97098292-43115380-16b6-11eb-8d72-e36ab9de4ea5.png)

**Comment by MiniBullLab** [comment]
测试生成mask图
@kingwangxiang

**Comment by kingwangxiang** [comment]
测最新EasyAiSampleMark标注工具(生成分割mask标签)：
1.分割标注生成的坐标json文件没有问题，可以记录标注对象外围轮廓坐标。
2.测试工具栏下的分割图生成器，两张测试图，无论选择标签图还是彩色图，能够生成两张图，其中测试图1.png生成结果不对，另一张正确。
![分割图生成测试](https://user-images.githubusercontent.com/37147736/97793941-dfdf6e00-1c2d-11eb-94f7-5eed3035d7ee.jpg)
![分割标注标签图](https://user-images.githubusercontent.com/37147736/97794154-3ef2b200-1c31-11eb-9008-24471d44265c.png)
3.生成的mask标签，边缘像素值存在差异，不是统一的值。
![分割mask边缘像素值不统一](https://user-images.githubusercontent.com/37147736/97794141-0521ab80-1c31-11eb-8f6a-8854cde66e88.jpg)
