### ISSUE TITLE
Segmentation fault (core dumped)问题

### ISSUE THREAD

**Issue by foww-0001** [MiniBullLab/easy_sample_mark#11]
* 1. 标注检测时，打开图片文件夹后，直接选择设置，手动标注参数设置，恢复默认值，点击保存。会出现闪退的情况。
* 2. 如果打开图片文件夹后，点击右侧的任意一张图片后，再去进行手动标注参数设置，恢复默认值，点击保存。则不会出现闪退情况。
* 3. 或是先进行设置，手动标注参数设置，恢复默认值，点击保存。然后打开图片文件夹，选择一张图片进行标注，也不会出现闪退情况。
 @lpj0822

**Comment by vitahlin** [comment]
`workspace` 测试时出现

**Comment by lpj0822** [comment]
该问题已经修改

> 测试过，问题已经解决。
