### ISSUE TITLE
测试windows下的标注工具

### ISSUE THREAD

**Issue by vitahlin** [MiniBullLab/easy_sample_mark#12]

**Comment by foww-0001** [comment]
测试windows下的标注工具，有如下错误:
load *.jpg图片报错，见下图:
![捕获](https://user-images.githubusercontent.com/69777191/112742454-468c6c00-8fc1-11eb-80f9-612a564d71fd.PNG)
load*.png则正常。
![捕获1](https://user-images.githubusercontent.com/69777191/112742462-602db380-8fc1-11eb-8c96-5eb0229645d0.PNG)

@lpj0822

**Comment by foww-0001** [comment]
其余功能测试并没有问题。
