### ISSUE TITLE
OCR测试

### ISSUE THREAD

**Issue by vitahlin** [MiniBullLab/easy_sample_mark#15]

**Comment by foww-0001** [comment]
1. 目前ocr可以检测框和字符是否正确，但是检查不了中间的属性是否标注出错。
2. seg中的标注回退的操作方式是点击右键吗
3. 属性栏的间距可以调大一点
4. 再选中是否模糊后还需要进行字符输入
5. 备注需要如何加入呢
6. 字符的标注显示结果可以用亮一点的颜色
@lpj0822 
> 2. ctrl-z可以回退到上一个标注点。
> 4. 这个会默认#作为字符输入，如果有字符可以进行修改。
> 5. 备注目前没用。
> 6. 这个自己调颜色。
