### ISSUE TITLE
建立标准的数据标注格式文档

### ISSUE THREAD

**Issue by foww-0001** [MiniBullLab/easy_sample_mark#8]

**Comment by MiniBullLab** [comment]
- [x] 1. 分类的标注格式
 - [x] 2. 检测的标注格式
 - [x] 3. 分割的标注格式
 - [x] 4. 人体姿态的标注格式
 - [x] 5. OCR
 - [x] 6. Key Point
 - [x] 7. Landmark
 - [x] 8. 实例分割
